# Copyright 2022-present, Lorenzo Bonicelli, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
    'seq-cifar10': {'sgd': {-1: {'lr': 0.1,
                                 'batch_size': 32,
                                 'n_epochs': 50}},
                    'ewc_on': {500: {'lr': 0.03,
                                    'e_lambda': 10,
                                    'gamma': 1.0,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 1}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                  'beta': 0.5,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                  'beta': 1.0,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           2000: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                    'beta': 0.5,
                                  'n_epochs': 50}},
                    'agem': {200: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             500: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             5120: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 50}},
                    'hal': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.2,
                                  'beta': 0.5,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.1,
                                  'beta': 0.3,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50,
                                   'hal_lambda': 0.1,
                                   'beta': 0.3,
                                   'gamma': 0.1,
                                   'steps_on_anchors': 100,
                                   'finetuning_epochs': 1}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              1000: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              2000: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 1.0,
                                     'batch_size': 32,
                                     'n_epochs': 50}}},
    'seq-tinyimg': {'sgd': {-1: {'lr': 0.03,
                                 'batch_size': 32,
                                 'n_epochs': 100}},
                    'ewc_on': {500: {'lr': 0.03,
                                    'e_lambda': 10,
                                    'gamma': 1.0,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 1}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'beta': 1.0,
                                 'n_epochs': 100},
                          2000: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                 'beta': 1.0,
                                  'n_epochs': 100}},
                    'agem': {200: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             500: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             5120: {'lr': 0.01,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'hal': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.2,
                                  'beta': 0.5,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.1,
                                  'beta': 0.5,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50,
                                   'hal_lambda': 0.1,
                                   'beta': 0.3,
                                   'gamma': 0.1,
                                   'steps_on_anchors': 100,
                                   'finetuning_epochs': 1}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              1000: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 100},
                              2000: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 100}}},
'seq-core50': {
        'derpp': {500: {
                        'lr': 0.03,
                        'batch_size' : 32,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 0.5,
                        'n_epochs': 20}},
        'ewc_on': {500: {'lr': 0.03,
                         'e_lambda': 10,
                         'gamma': 1.0,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 1}},
        'er': {200: {'lr': 0.03,
                     'minibatch_size': 32,
                     'batch_size': 32,
                     'n_epochs': 20},
               500: {'lr': 0.03,
                     'minibatch_size': 32,
                     'batch_size': 32,
                     'beta': 1.0,
                     'n_epochs': 20},
               2000: {'lr': 0.1,
                      'minibatch_size': 32,
                      'batch_size': 32,
                      'beta': 1.0,
                      'n_epochs': 20}},
        'hal': {200: {'lr': 0.1,
                  'minibatch_size': 128,
                  'batch_size': 128,
                  'hal_lambda': 0.1,
                  'beta': 0.5,
                  'gamma': 0.1,
                  'n_epochs': 20},
            500: {'lr': 0.03,
                  'minibatch_size': 32,
                  'batch_size': 32,
                  'hal_lambda': 0.1,
                  'beta': 0.3,
                  'gamma': 0.1,
                  'n_epochs': 20},
            5120: {'lr': 0.1,
                   'minibatch_size': 128,
                   'batch_size': 128,
                   'hal_lambda': 0.1,
                   'beta': 0.5,
                   'gamma': 0.1,
                   'n_epochs': 20}},
        'agem': {200: {'lr': 0.01,
                       'minibatch_size': 32,
                       'batch_size': 32,
                       'n_epochs': 20},
                 500: {'lr': 0.01,
                       'minibatch_size': 32,
                       'batch_size': 32,
                       'n_epochs': 20},
                 5120: {'lr': 0.01,
                        'minibatch_size': 32,
                        'batch_size': 32,
                        'n_epochs': 20}}},
'seq-cifar100': {
        'sgd': {-1: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0}},
        'er': {500: {'lr': 0.1, 'optim_mom': 0, 'beta': 0.5, 'optim_wd': 0},
               100: {'lr': 0.1, 'optim_mom': 0, 'beta': 0.5, 'optim_wd': 0},
               1000: {'lr': 0.1, 'optim_mom': 0, 'beta': 0.5, 'optim_wd': 0},
               200: {'lr': 0.1, 'optim_mom': 0, 'beta': 0.5, 'optim_wd': 0}},
        'ewc_on': {500: {'lr': 0.03,
                         'e_lambda': 10,
                         'gamma': 1.0,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 1}},
        'agem': {200: {'lr': 0.03,
                       'minibatch_size': 32,
                       'batch_size': 32,
                       'n_epochs': 50},
                 500: {'lr': 0.03,
                       'minibatch_size': 32,
                       'batch_size': 32,
                       'n_epochs': 50},
                 5120: {'lr': 0.03,
                        'minibatch_size': 32,
                        'batch_size': 32,
                        'n_epochs': 50}},
        'derpp': {
            100: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5},
            200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 50},
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 50},
            1000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5},
            2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5}
        },
        'hal': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.2,
                                  'beta': 0.5,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.1,
                                  'beta': 0.3,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50,
                                   'hal_lambda': 0.1,
                                   'beta': 0.3,
                                   'gamma': 0.1,
                                   'steps_on_anchors': 100,
                                   'finetuning_epochs': 1}}
        }
    }
